### ISSUE TITLE
OpenAI API Permissions

### ISSUE THREAD

**Issue by 42piratas** [42piratas/VOTEgpt#22]
![image](https://github.com/user-attachments/assets/f2930bcb-3a84-40ce-867f-3ea0d56700b2)

**Comment by 42piratas** [comment]
@thiagopbraga Please, let me know what permissions I should set. 

Let's open only the minimum necessary endpoints, please.

**Comment by thiagopbragafuturo** [comment]
Initially we only need the _v1/chat/completions_ endpoint that performs the "conversation" with chatgpt. So we can have just write permission on **Model capabilities**

**Comment by 42piratas** [comment]
✅
